-- Kairo — table des startups suivies
-- A executer une seule fois dans Supabase > SQL Editor

create table if not exists startups (
  id bigint generated by default as identity primary key,
  name text not null,
  sector text not null,
  website_domain text not null,      -- ex: mistral.ai (sert a generer le logo via Clearbit)
  github_org text,                    -- ex: mistralai (organisation GitHub, peut etre vide)
  score numeric not null default 50,  -- score de momentum 0-100 (fictif pour l'instant)
  delta numeric not null default 0,   -- variation en % (fictif pour l'instant)
  signal_funding numeric not null default 50,
  signal_github numeric not null default 50,
  signal_trends numeric not null default 50,
  signal_press numeric not null default 50,
  blurb text,
  created_at timestamptz not null default now()
);

insert into startups (name, sector, website_domain, github_org, score, delta, signal_funding, signal_github, signal_trends, signal_press, blurb) values
('Mistral AI', 'IA générative', 'mistral.ai', 'mistralai', 87, 4.2, 92, 78, 91, 85, 'Forte activité presse et communauté open source active'),
('Poolside', 'Dev tools IA', 'poolside.ai', 'poolsideai', 73, -1.8, 88, 45, 60, 55, 'Croissance stable, peu de bruit médiatique cette semaine'),
('Photoroom', 'IA visuelle', 'photoroom.com', 'Photoroom', 81, 6.5, 70, 60, 88, 78, 'Pic de mentions suite à une nouvelle fonctionnalité'),
('Dust', 'Agents IA entreprise', 'dust.tt', 'dust-tt', 68, 2.1, 65, 72, 62, 58, 'Adoption croissante en entreprise, repo actif'),
('Pennylane', 'Fintech / comptabilité', 'pennylane.com', 'pennylane-hq', 66, 1.4, 72, 30, 55, 50, 'Expansion régulière sur le marché des PME'),
('Payfit', 'HR Tech / paie', 'payfit.com', 'PayFit', 76, 1.2, 80, 20, 68, 70, 'Expansion européenne confirmée, embauches en hausse'),
('Alan', 'Assurtech / santé', 'alan.com', 'alan-eu', 71, 0.4, 75, 25, 60, 62, 'Croissance régulière, pas de signal fort cette semaine'),
('Qonto', 'Fintech / banque pro', 'qonto.com', 'qonto', 79, 2.8, 82, 35, 70, 75, 'Levée récente et forte visibilité presse'),
('Ledger', 'Cybersécurité / crypto', 'ledger.com', 'LedgerHQ', 62, -2.5, 50, 68, 55, 48, 'Marché crypto volatil, sentiment mitigé'),
('Swile', 'Fintech / avantages salariés', 'swile.co', 'Swile', 58, -0.8, 55, 22, 50, 45, 'Activité stable, peu d’actualité récente'),
('Contentsquare', 'Analytics / expérience digitale', 'contentsquare.com', 'ContentSquare', 64, 0.9, 68, 40, 58, 52, 'Croissance continue sur le marché enterprise'),
('Aircall', 'SaaS / téléphonie cloud', 'aircall.io', 'aircall', 60, -1.1, 58, 38, 52, 47, 'Marché compétitif, croissance modérée'),
('Lucca', 'HR Tech / SIRH', 'lucca.fr', 'LuccaSA', 55, 0.3, 52, 28, 45, 42, 'Positionnement stable sur le marché français'),
('Comet ML', 'MLOps / IA', 'comet.com', 'comet-ml', 70, 3.0, 60, 75, 65, 55, 'Portée par l’essor général des outils MLOps'),
('Blablacar', 'Mobilité / covoiturage', 'blablacar.com', 'blablacar', 57, -0.5, 45, 42, 55, 50, 'Activité saisonnière, stable hors périodes de vacances'),
('Sorare', 'Web3 / fantasy sport', 'sorare.com', 'sorare', 44, -5.9, 30, 30, 55, 40, 'Sentiment en baisse dans la presse spécialisée'),
('Pigment', 'SaaS / planification d’entreprise', 'pigment.com', 'gopigment', 59, -3.4, 55, 20, 48, 45, 'Activité en ralentissement, pas d’annonce récente'),
('Doctolib', 'HealthTech', 'doctolib.fr', 'doctolib', 74, 1.6, 78, 32, 65, 68, 'Leader stable du marché santé français'),
('Back Market', 'E-commerce reconditionné', 'backmarket.com', 'BackMarket', 63, -1.3, 60, 35, 58, 50, 'Marché du reconditionné en normalisation'),
('Shine', 'Fintech / néobanque indépendants', 'shine.fr', 'shinetools', 56, 0.6, 50, 25, 48, 44, 'Croissance régulière sur le segment freelances');
