-- Kairo — pivot vers un modèle "capital + dilution" réaliste, à la place du
-- score composite qui fixait un prix arbitraire par part (voir 002_pivot_formula.sql
-- et lib/scoring/config.js pour l'ancien système).
--
-- Principe : un utilisateur achète un % de capital d'une startup, calculé à la
-- valorisation post-money du dernier tour connu. Quand un nouveau tour est
-- détecté, toutes les positions existantes sur cette startup sont diluées
-- proportionnellement (pas de clause anti-dilution — cas simple retenu pour
-- le MVP, voir brief).
--
-- Migration ADDITIVE UNIQUEMENT : ne touche pas aux tables portfolio/holdings
-- existantes (005/006_user_accounts.sql). L'app continue de fonctionner avec
-- l'ancien système tant que le code n'a pas basculé dessus (voir todo "Refondre
-- l'UI"). La table "portfolio" (cash en K¢) est réutilisée telle quelle.
--
-- A executer une seule fois dans Supabase > SQL Editor, après 006_user_accounts.sql.

-- Cycle de vie d'une startup : active (par défaut), exited (rachat, voir
-- settle_exit ci-dessous), defunct (faillite, voir settle_bankruptcy).
-- "stage" est purement indicatif pour l'affichage (early/growth/late).
alter table startups add column if not exists stage text check (stage in ('early','growth','late'));
alter table startups add column if not exists lifecycle_status text not null default 'active' check (lifecycle_status in ('active','exited','defunct'));
alter table startups add column if not exists exit_price_eur numeric;
alter table startups add column if not exists exit_date date;

-- Historique des tours de financement connus pour chaque startup. Une ligne =
-- un tour, avec sa valorisation post-money et sa source (Pappers plus tard,
-- presse ou saisie manuelle sourcée en attendant — jamais une estimation
-- inventée, voir brief "100% des startups doivent avoir une valorisation
-- sourcée publiquement").
create table if not exists financing_rounds (
  id bigint generated by default as identity primary key,
  startup_id bigint not null references startups(id) on delete cascade,
  round_date date not null,
  round_label text,               -- ex: "Série B" (peut être inconnu)
  amount_eur numeric,             -- montant levé (peut être inconnu si seule la valo est sourcée)
  pre_money_eur numeric,
  post_money_eur numeric not null,
  source_type text not null check (source_type in ('pappers', 'press', 'manual')),
  source_ref text,                -- URL article, id d'acte Pappers, etc. (traçabilité)
  precision_note text,            -- ex: "arrondi au 10M€ près, structure actions de préférence non prise en compte"
  created_at timestamptz not null default now()
);
create index if not exists financing_rounds_startup_date_idx on financing_rounds (startup_id, round_date desc);

-- Positions des utilisateurs, en % de capital détenu (remplace le nombre de
-- "parts" arbitraire de la table holdings). invested_kc est indicatif (coût
-- d'entrée cumulé en K¢, pour calculer une plus/moins-value affichée), il ne
-- sert jamais à calculer la valeur actuelle (qui dépend de la valorisation
-- courante, pas du prix payé).
create table if not exists positions (
  user_id uuid not null references auth.users(id) on delete cascade,
  startup_id bigint not null references startups(id) on delete cascade,
  equity_pct numeric not null default 0,
  invested_kc numeric not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, startup_id)
);
alter table positions enable row level security;
create policy "Chacun gere ses propres positions"
  on positions for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Valorisation courante d'une startup = post-money du tour le plus récent
-- connu. Vue pratique pour l'app (achat) et pour le pipeline de refresh.
create or replace view startup_valuations as
select distinct on (startup_id)
  startup_id,
  post_money_eur as current_post_money_eur,
  round_date as last_round_date
from financing_rounds
order by startup_id, round_date desc;

-- Appelée par le pipeline de sourcing (Pappers plus tard, script manuel en
-- attendant) quand un nouveau tour est détecté pour une startup suivie :
-- enregistre le tour, puis dilue proportionnellement toutes les positions
-- existantes sur cette startup (equity_pct *= ancienne_valo / nouvelle_valo).
-- security definer (comme handle_new_user en 006) pour pouvoir mettre à jour
-- les positions de TOUS les utilisateurs, pas seulement l'appelant — cette
-- fonction n'est jamais appelée directement par un utilisateur final.
create or replace function public.record_financing_round(
  p_startup_id bigint,
  p_round_date date,
  p_post_money_eur numeric,
  p_amount_eur numeric default null,
  p_pre_money_eur numeric default null,
  p_round_label text default null,
  p_source_type text default 'manual',
  p_source_ref text default null,
  p_precision_note text default null
) returns void as $$
declare
  v_old_post_money numeric;
begin
  select current_post_money_eur into v_old_post_money
  from startup_valuations where startup_id = p_startup_id;

  insert into financing_rounds
    (startup_id, round_date, round_label, amount_eur, pre_money_eur, post_money_eur, source_type, source_ref, precision_note)
  values
    (p_startup_id, p_round_date, p_round_label, p_amount_eur, p_pre_money_eur, p_post_money_eur, p_source_type, p_source_ref, p_precision_note);

  if v_old_post_money is not null and v_old_post_money > 0 then
    update positions
    set equity_pct = equity_pct * (v_old_post_money / p_post_money_eur),
        updated_at = now()
    where startup_id = p_startup_id;
  end if;
end;
$$ language plpgsql security definer set search_path = public;

-- "Exit" (rachat) : tous les détenteurs touchent equity_pct × prix de rachat,
-- crédité en cash (converti en K¢ au même taux que l'achat, voir lib/market.js
-- EUR_PER_KC), puis leur position est remise à zéro. La startup passe en
-- lifecycle_status = 'exited' et n'est plus investissable.
create or replace function public.settle_exit(
  p_startup_id bigint,
  p_exit_price_eur numeric,
  p_eur_per_kc numeric,
  p_exit_date date default current_date
) returns void as $$
begin
  update startups
  set lifecycle_status = 'exited', exit_price_eur = p_exit_price_eur, exit_date = p_exit_date
  where id = p_startup_id;

  update portfolio p
  set cash = p.cash + (pos.equity_pct * p_exit_price_eur / p_eur_per_kc),
      updated_at = now()
  from positions pos
  where pos.user_id = p.user_id and pos.startup_id = p_startup_id and pos.equity_pct > 0;

  update positions set equity_pct = 0, updated_at = now() where startup_id = p_startup_id;
end;
$$ language plpgsql security definer set search_path = public;

-- Faillite / disparition : positions remises à zéro, aucun paiement. La
-- startup passe en lifecycle_status = 'defunct' et n'est plus investissable.
create or replace function public.settle_bankruptcy(p_startup_id bigint) returns void as $$
begin
  update startups set lifecycle_status = 'defunct' where id = p_startup_id;
  update positions set equity_pct = 0, updated_at = now() where startup_id = p_startup_id;
end;
$$ language plpgsql security definer set search_path = public;
