-- Kairo — modèle "valorisation relative" (remplace la dilution par cap table
-- réel — voir 007/009 — par un indice fictif qui oscille autour d'une ancre).
-- Contexte complet : brief du 2026-07-23 ("modèle A"). Comme la monnaie du
-- jeu (K¢) est déjà fictive, ce qui compte n'est plus la précision de la
-- valorisation réelle en € mais (1) l'ordre de grandeur relatif entre
-- startups et (2) le mouvement dans le temps — pour rendre le jeu vivant.
--
-- Principe : chaque startup garde une ANCRE (la dernière levée réelle
-- confirmée, sourcée presse — inchangé, voir financing_rounds/
-- startup_valuations) mais la valeur AFFICHÉE/investissable oscille autour
-- de cette ancre via valuation_offset_pct, mis à jour une fois par jour par
-- le pipeline (voir app/api/refresh-valuations/route.js) selon deux
-- dimensions cumulatives :
--   1. Tendance de fond (mouvement lent) : moyenne glissante du sentiment
--      presse sur ~14 jours -> dérive douce (±0,3%/jour max).
--   2. Buzz (mouvement rapide) : pic anormal de mentions/sentiment un jour
--      donné (écart significatif p/r à l'historique propre de la startup) ->
--      à-coup ponctuel, plus fort en négatif qu'en positif (un scandale doit
--      faire plus mal qu'une bonne nouvelle ne fait du bien).
-- L'écart courant se réduit d'environ 10%/jour (retour progressif vers
-- l'ancre, le buzz "retombe"), et reste plafonné à ±40% pour éviter toute
-- dérive incontrôlée tant qu'aucune nouvelle levée réelle n'est intervenue.
-- Une nouvelle levée réelle confirmée déplace l'ancre ET réinitialise
-- l'écart à 0 (on repart d'une référence fraîche).
--
-- IMPORTANT : ce modèle SUPPRIME la dilution des positions existantes lors
-- d'un nouveau tour réel (record_financing_round ne touche plus `positions`)
-- — cohérent avec "ce qui compte c'est le relatif et l'évolution, pas le
-- cap table réel". Une fois un % acheté, il reste fixe ; seule la valeur
-- oscille, comme une action en bourse.
--
-- Migration ADDITIVE (n'efface aucune donnée existante) sauf le corps de
-- record_financing_round, qui est réécrit (create or replace).
--
-- A executer une seule fois dans Supabase > SQL Editor, après 010_notifications.sql.

-- 1) Écart courant à l'ancre, en fraction (0.05 = +5%, -0.12 = -12%).
alter table startups add column if not exists valuation_offset_pct numeric not null default 0;

-- 2) Historique quotidien du signal presse par startup (mentions + ton du
-- jour) — nécessaire pour calculer la moyenne glissante (tendance) et
-- détecter les écarts anormaux (buzz) propres à CHAQUE startup (le "normal"
-- de Mistral AI n'est pas celui de K-Ren). sentiment_score : moyenne des
-- articles du jour classés -1 (négatif) / 0 (neutre/ambigu) / +1 (positif) —
-- voir lib/scoring/sources/sentiment.js. NULL si aucune mention ce jour-là
-- (silence médiatique, pas un signal négatif — voir press.js).
create table if not exists signal_history (
  id bigint generated by default as identity primary key,
  startup_id bigint not null references startups(id) on delete cascade,
  observed_date date not null,
  mentions_count integer not null default 0,
  sentiment_score numeric,
  created_at timestamptz not null default now(),
  unique (startup_id, observed_date)
);
create index if not exists signal_history_startup_idx on signal_history (startup_id, observed_date desc);

-- 3) record_financing_round : ne dilue plus les positions existantes (voir
-- contexte ci-dessus). Un nouveau tour réel déplace juste l'ancre et remet
-- l'oscillation à 0. Signature inchangée (compatible avec tous les appels
-- existants de 008_roster_v2.sql).
create or replace function public.record_financing_round(
  p_startup_id bigint,
  p_round_date date,
  p_post_money_eur numeric,
  p_amount_eur numeric default null,
  p_pre_money_eur numeric default null,
  p_round_label text default null,
  p_source_type text default 'manual',
  p_source_ref text default null,
  p_precision_note text default null
) returns void as $$
begin
  insert into financing_rounds
    (startup_id, round_date, round_label, amount_eur, pre_money_eur, post_money_eur, source_type, source_ref, precision_note, event_type)
  values
    (p_startup_id, p_round_date, p_round_label, p_amount_eur, p_pre_money_eur, p_post_money_eur, p_source_type, p_source_ref, p_precision_note, 'financing_round');

  update startups set valuation_offset_pct = 0 where id = p_startup_id;
end;
$$ language plpgsql security definer set search_path = public;

-- 4) record_secondary_valuation : idem, ne diluait déjà pas ; on aligne
-- juste le comportement (réinitialise aussi l'écart à 0 sur une nouvelle
-- référence de marché secondaire).
create or replace function public.record_secondary_valuation(
  p_startup_id bigint,
  p_post_money_eur numeric,
  p_round_date date,
  p_source_type text default 'press',
  p_source_ref text default null,
  p_precision_note text default null
) returns bigint as $$
declare
  v_round_id bigint;
begin
  insert into financing_rounds
    (startup_id, round_date, round_label, amount_eur, pre_money_eur, post_money_eur, source_type, source_ref, precision_note, event_type)
  values
    (p_startup_id, p_round_date, 'Marché secondaire', null, null, p_post_money_eur, p_source_type, p_source_ref, p_precision_note, 'secondary_market')
  returning id into v_round_id;

  update startups set valuation_offset_pct = 0 where id = p_startup_id;

  return v_round_id;
end;
$$ language plpgsql security definer set search_path = public;

-- 5) Dix nouvelles petites startups (valorisées sous 5-6 M€), pour varier
-- l'échelle du roster. Comme la plupart des articles sourcés pour des tours
-- seed/pré-seed ne publient pas de valorisation post-money explicite
-- (contrairement à Mistral/Aircall), l'ancre est approximée par le MONTANT
-- LEVÉ (montant confirmé en presse), plutôt que d'inventer un post-money —
-- toujours documenté en precision_note, cohérent avec la philosophie du
-- projet ("un ordre de grandeur correct suffit", voir 009). Axion-IA exclue
-- : aucune levée sourcée par un article de presse fiable trouvée.
insert into startups (name, sector, website_domain, github_org, blurb) values
('Dploy', 'AdTech / audio in-store', 'dploy.audio', null, 'Transforme le système sonore des magasins en canal média programmatique, ciblage temps réel selon lieu, météo et activité commerciale.'),
('Orakle Weather', 'Assurtech / assurance paramétrique', 'orakleweather.com', null, 'Assurance météo intelligente qui indemnise automatiquement les voyageurs en cas de pluie, neige ou grêle dépassant un seuil.'),
('Kacentric Optics', 'Photonique / instrumentation', 'kacentric.com', null, 'Développe des instruments de test et mesure en photonique (spectroscopie d''absorption) pour applications industrielles et scientifiques.'),
('W Platform', 'GreenTech / valorisation CO2', 'w-platform.fr', null, 'Capte et valorise le CO2 issu de la fermentation (vignobles, brasseries) pour en faire une ressource industrielle.'),
('K-Ren', 'GreenTech / nautisme', 'k-ren.fr', null, 'Housse textile écologique qui remplace les peintures antifouling polluantes sur les coques de bateaux.'),
('Objow', 'SaaS / performance commerciale', 'objow.com', null, 'Plateforme SaaS de gamification pour animer la performance commerciale et le coaching quotidien des équipes de vente.'),
('Ellipse Bikes', 'Mobilité électrique / vélos connectés', 'ellipsebikes.com', null, 'Fabricant troyen de vélos utilitaires connectés (clignotants, GPS, alarme intégrés), avec offre de leasing pour entreprises.'),
('Rivage (Proptech)', 'Proptech / gestion locative', 'rivage.immo', null, 'Logiciel tout-en-un de gestion locative et comptabilité immobilière avec agent IA, pour administrateurs de biens.'),
('Rivage (Paie)', 'Fintech RH / paie', 'rivage.tech', null, 'Logiciel de paie ouvert et interopérable destiné aux cabinets d''expertise comptable et à leurs clients TPE/PME.'),
('Twinsight', 'Medtech / chirurgie assistée par IA', 'twinsight-medical.com', null, 'Éditeur de SurgiTwin, plateforme de jumeau numérique par IA pour la planification de chirurgie orthopédique du genou.');

select record_financing_round((select id from startups where name = 'Dploy'), '2026-02-01', 500000, 500000, null, 'Business angels', 'press', 'https://www.open-garden.com/p/midia-devient-dploy-et-leve-500-000-euros-pour-industrialiser-la-pub-audio-in-store', 'Ancre = montant levé (pas de post-money publié) ; date exacte de l''article non confirmée avec précision, rebranding MidiA -> Dploy en 2026.');
select record_financing_round((select id from startups where name = 'Orakle Weather'), '2026-05-29', 550000, 550000, null, 'Seed', 'press', 'https://www.maddyness.com/2026/05/29/les-startups-francaises-ont-leve-465-millions-deuros-cette-semaine/', 'Ancre = montant levé (pas de post-money publié).');
select record_financing_round((select id from startups where name = 'Kacentric Optics'), '2025-06-01', 1200000, 1200000, null, 'Seed', 'press', 'https://www.lejournaldesentreprises.com/breve/photonique-kacentric-optics-leve-12-million-deuros-et-devrait-lancer-son-premier-produit-en-2027-2142375', 'Ancre = montant levé (pas de post-money publié) ; date exacte de l''article non confirmée, ordre de grandeur seulement.');
select record_financing_round((select id from startups where name = 'W Platform'), '2026-07-15', 1000000, 1000000, null, 'Tour 2026', 'press', 'https://www.bougerabordeaux.com/actu/news/la-start-up-bordelaise-w-platform-leve-1-million-deuros-pour-transformer-le-co2-en-ressource/', 'Ancre = montant levé (pas de post-money publié) ; fait suite à une première levée de 2 M€ en mars 2024, non reprise ici (on garde le tour le plus récent).');
select record_financing_round((select id from startups where name = 'K-Ren'), '2026-05-21', 1200000, 1200000, null, 'Augmentation de capital', 'press', 'https://www.boatindustry.fr/article/51937/k-ren-accelere-son-industrialisation-et-leve-1-2-me', 'Ancre = montant levé (pas de post-money publié) ; 400 000€ d''obligations convertibles complémentaires non inclus.');
select record_financing_round((select id from startups where name = 'Objow'), '2024-12-08', 2000000, 2000000, null, 'Tour 2024', 'press', 'https://www.jaimelesstartups.fr/news/objow-annonce-une-levee-de-2-millions-deuros/', 'Ancre = montant levé, dont 500 000€ de dette (pas de post-money publié).');
select record_financing_round((select id from startups where name = 'Ellipse Bikes'), '2026-03-01', 1500000, 1500000, null, 'Premier tour', 'press', 'https://www.lejournaldesentreprises.com/article/ellipse-bikes-boucle-une-levee-de-fonds-de-15-million-deuros-pour-completer-son-offre-de-velos-pour-2143417', 'Ancre = montant levé (pas de post-money publié) ; date exacte de l''article non confirmée avec précision.');
select record_financing_round((select id from startups where name = 'Rivage (Proptech)'), '2026-07-06', 1500000, 1500000, null, 'Seed', 'press', 'https://www.journaldunet.com/start-up/1552255-rivage-leve-1-5-million-d-euros-pour-sa-plateforme-de-gestion-immobiliere/', 'Ancre = montant levé (pas de post-money publié) ; à ne pas confondre avec Rivage (Paie), homonyme sans lien.');
select record_financing_round((select id from startups where name = 'Rivage (Paie)'), '2026-02-12', 2600000, 2600000, null, 'Pré-seed', 'press', 'https://www.planet-fintech.com/Rivage-leve-26-M-aupres-de-Partech-pour-accelerer-le-deploiement-de-son-logiciel-de-paie_a7031.html', 'Ancre = montant levé (pas de post-money publié) ; à ne pas confondre avec Rivage (Proptech), homonyme sans lien.');
select record_financing_round((select id from startups where name = 'Twinsight'), '2026-07-23', 1600000, 1600000, null, 'Seed', 'press', 'https://www.lejournaldesentreprises.com/breve/la-jeune-pousse-twinshight-leve-16-million-pour-accelerer-son-developpement-aux-etats-unis-2147061', 'Ancre = montant levé (pas de post-money publié).');

-- 6) Stade indicatif pour les 10 nouvelles (toutes < 6 M€ -> 'early').
update startups set stage = 'early'
where name in ('Dploy', 'Orakle Weather', 'Kacentric Optics', 'W Platform', 'K-Ren', 'Objow', 'Ellipse Bikes', 'Rivage (Proptech)', 'Rivage (Paie)', 'Twinsight');
