-- Kairo — clubs (mini-championnats entre amis), en complément du classement
-- général (014_profiles_and_leaderboard.sql). Voir échange du 2026-07-24 :
-- "un classement général de tous les utilisateurs, ET un système de
-- clans/clubs où l'on peut créer un club, ajouter ses amis, et avoir un
-- mini-championnat".
--
-- Pas de système d'amis/recherche d'utilisateurs dans Kairo aujourd'hui (et
-- ça ouvrirait des questions de vie privée : chercher un utilisateur par
-- pseudo, harcèlement potentiel, etc.) -> on retient le mécanisme le plus
-- simple et le plus sûr pour "ajouter ses amis" : un CODE D'INVITATION
-- (comme Discord/Kahoot). Le créateur du club obtient un code, le partage
-- hors de Kairo (WhatsApp, SMS...) à qui il veut, et n'importe qui muni du
-- code peut rejoindre. Pas besoin de savoir qui existe sur la plateforme.
--
-- Écritures verrouillées derrière deux fonctions security definer
-- (create_club, join_club, même principe que record_financing_round/
-- settle_exit en 007_equity_model.sql) plutôt que des policies RLS INSERT
-- ouvertes sur club_members : une policy "auth.uid() = user_id" sur INSERT
-- permettrait à n'importe qui de s'ajouter à N'IMPORTE QUEL club (le
-- club_id est un simple bigint devinable), sans jamais passer par le code
-- d'invitation. Le code n'a de valeur de sécurité que s'il est le SEUL
-- chemin pour rejoindre.
--
-- A executer une seule fois dans Supabase > SQL Editor, après
-- 014_profiles_and_leaderboard.sql (les vues ci-dessous dépendent de
-- portfolio_values et public_profiles).

-- 1) Clubs et membres.
create table if not exists clubs (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) > 0),
  owner_id uuid not null references auth.users(id) on delete cascade,
  invite_code text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists club_members (
  club_id bigint not null references clubs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (club_id, user_id)
);

alter table clubs enable row level security;
alter table club_members enable row level security;

-- Lecture : uniquement les clubs dont on est membre (donc uniquement leurs
-- codes d'invitation aussi, ce qui permet à n'importe quel membre — pas
-- seulement le créateur — d'inviter d'autres amis en repartageant le code).
drop policy if exists "Voir les clubs dont on est membre" on clubs;
create policy "Voir les clubs dont on est membre"
  on clubs for select
  using (exists (select 1 from club_members cm where cm.club_id = clubs.id and cm.user_id = auth.uid()));

-- Renommage réservé au créateur (seule écriture directe autorisée sur clubs ;
-- la création elle-même passe par create_club ci-dessous).
drop policy if exists "Le createur peut renommer son club" on clubs;
create policy "Le createur peut renommer son club"
  on clubs for update
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

-- Lecture des membres : uniquement pour les clubs dont on fait soi-même
-- partie (sous-requête auto-référencée sur club_members, motif RLS standard).
drop policy if exists "Voir les membres de ses propres clubs" on club_members;
create policy "Voir les membres de ses propres clubs"
  on club_members for select
  using (exists (select 1 from club_members cm2 where cm2.club_id = club_members.club_id and cm2.user_id = auth.uid()));

-- Quitter un club : seule écriture directe autorisée sur club_members (join
-- passe par join_club/create_club, pas par un insert direct — voir plus haut).
drop policy if exists "Chacun peut quitter un club" on club_members;
create policy "Chacun peut quitter un club"
  on club_members for delete
  using (auth.uid() = user_id);

-- Nettoyage : un club sans plus aucun membre (dernier membre parti) est
-- supprimé automatiquement plutôt que de laisser une ligne orpheline
-- invisible (personne n'a plus le droit de la lire, RLS SELECT ci-dessus).
create or replace function public.cleanup_empty_club()
returns trigger as $$
begin
  if not exists (select 1 from public.club_members where club_id = old.club_id) then
    delete from public.clubs where id = old.club_id;
  end if;
  return old;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists on_club_member_deleted on club_members;
create trigger on_club_member_deleted
  after delete on club_members
  for each row execute function public.cleanup_empty_club();

-- 2) Créer un club : génère un code d'invitation à 8 caractères, crée la
-- ligne clubs, et ajoute automatiquement le créateur comme premier membre.
-- security definer car club_members n'a aucune policy INSERT ouverte (voir
-- plus haut) — c'est le seul chemin pour peupler club_members à la création.
create or replace function public.create_club(p_name text)
returns clubs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_club clubs;
  v_code text;
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Non authentifié';
  end if;
  if length(trim(coalesce(p_name, ''))) = 0 then
    raise exception 'Nom de club invalide';
  end if;

  loop
    v_code := upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8));
    begin
      insert into public.clubs (name, owner_id, invite_code)
      values (trim(p_name), v_uid, v_code)
      returning * into v_club;
      exit;
    exception when unique_violation then
      -- Collision sur invite_code (improbable sur 8 caractères) : on
      -- retente avec un nouveau code généré.
    end;
  end loop;

  insert into public.club_members (club_id, user_id) values (v_club.id, v_uid);

  return v_club;
end;
$$;

-- 3) Rejoindre un club via son code d'invitation. security definer pour la
-- même raison que create_club : c'est le seul chemin autorisé vers un insert
-- dans club_members pour quelqu'un d'autre que soi-même... même pour
-- soi-même en fait, puisqu'aucune policy INSERT directe n'existe.
create or replace function public.join_club(p_invite_code text)
returns clubs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_club clubs;
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Non authentifié';
  end if;

  select * into v_club from public.clubs where invite_code = upper(trim(coalesce(p_invite_code, '')));
  if not found then
    raise exception 'Code d''invitation invalide';
  end if;

  insert into public.club_members (club_id, user_id)
  values (v_club.id, v_uid)
  on conflict (club_id, user_id) do nothing;

  return v_club;
end;
$$;

-- 4) Vue pratique : mes clubs, avec nombre de membres (calculée côté SQL
-- plutôt que côté client pour ne pas avoir à charger tous les membres juste
-- pour les compter). Comme leaderboard/portfolio_values (014), créée par un
-- rôle BYPASSRLS -> peut compter tous les membres de club_members malgré sa
-- RLS, mais le "where" ci-dessous restreint quand même le résultat aux seuls
-- clubs de l'appelant (auth.uid()), donc pas de fuite vers les clubs des
-- autres.
create or replace view my_clubs as
select
  c.id,
  c.name,
  c.invite_code,
  c.owner_id,
  c.created_at,
  (select count(*) from club_members cm2 where cm2.club_id = c.id) as member_count
from clubs c
where exists (select 1 from club_members cm where cm.club_id = c.id and cm.user_id = auth.uid())
order by c.created_at desc;

-- 5) Mini-classement par club : mêmes colonnes que leaderboard (jamais le
-- cash/positions de quelqu'un d'autre), mais restreint aux clubs dont
-- l'appelant (auth.uid()) fait partie — le "where" final est ce qui rend
-- cette vue sûre malgré le BYPASSRLS de son propriétaire.
create or replace view club_leaderboard as
select
  cm.club_id,
  c.name as club_name,
  pr.display_name,
  pv.total_value_kc
from club_members cm
join clubs c on c.id = cm.club_id
join public_profiles pr on pr.user_id = cm.user_id
join portfolio_values pv on pv.user_id = cm.user_id
where cm.club_id in (select club_id from club_members where user_id = auth.uid())
order by cm.club_id, pv.total_value_kc desc;
